apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-affinity
  name: node-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-affinity
  strategy: {}
  template:
    metadata:
      labels:
        app: node-affinity
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: disktype
                operator: In
                values: 
                - test
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: gpu
                operator: Exists  
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
