apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pod-affinity
  name: pod-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-affinity
  strategy: {}
  template:
    metadata:
      labels:
        app: pod-affinity
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: node-affinity
            topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                   app: pod-affinity
              topologyKey: kubernetes.io/hostname
                
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
