apiVersion: v1
kind: Pod
metadata:
  name: sidecar-success-demo
spec:
  volumes:
    - name: logs
      emptyDir: {}
  initContainers:
    - name: log-reader
      image: busybox
      restartPolicy: Always  #sidecar container
      command:
        - sh
        - -c
        - |
          touch /var/log/app.log
          tail -F /var/log/app.log
      volumeMounts:
        - name: logs
          mountPath: /var/log
  containers:
    - name: app
      image: busybox
      command:
        - sh
        - -c
        - |
          while true; do
            echo "hello from app - $(date +"%H:%M:%S")" >> /var/log/app.log
            sleep 5
          done
      volumeMounts:
        - name: logs
          mountPath: /var/log