apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod
spec:
  initContainers:
  - image: nginx
    name: pod-1
    command: ['sh', '-c', "echo 'Better code together' && exit 1"]
  containers:
  - image: nginx
    name: pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}