apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngx-deploy
  name: ngx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngx-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: ngx-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ngx-deploy
  name: ngx-deploy-clusterip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngx-deploy
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ngx-deploy
  name: ngx-deploy-nodeport
spec:
  type: NodePort
  selector:
    app: ngx-deploy
  ports:
    - name: http
      port: 80          # porta esposta dal Service dentro il cluster
      targetPort: 80    # porta sul Pod
      protocol: TCP
      nodePort: 30080   # porta sul nodo (range 30000-32767)
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ngx-deploy
  name: ngx-deploy-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: ngx-deploy
  ports:
    - name: http
      port: 80        # porta esposta dal LB
      targetPort: 80  # porta sul Pod
      protocol: TCP
