apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 3Gi
    limits.cpu: "7"
    limits.memory: 7Gi
    pods: "5"
    configmaps: "1"