apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels:
    app: test
    tier: be
spec:
  containers:
    - name: test-spring
      image: gemod/test-spring-color-1:1.2
      env:
      - name: GREETING_PREFIX
        valueFrom:
          configMapKeyRef:
            name: spring-app-config
            key: greeter.prefix
