apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  volumes:
    - name: shared
      emptyDir: {}
  containers:
  - name: writer
    image: busybox
    command: ['sh', '-c', 'echo "hello da writer!" > /data/msg.txt && sleep 3600']
    volumeMounts:
    - name: shared
      mountPath: /data
  - name: reader
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: shared
      mountPath: /data