apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  volumes:
    - name: host-data
      hostPath:
        path: /tmp/k8s-demo
        type: DirectoryOrCreate
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: host-data
      mountPath: /data