apiVersion: v1
kind: Pod
metadata:
  name: pod-resource-test
spec:
  containers:
  - image: nginx
    name: pod-resource-test
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: "1"
        memory: 1Gi
