apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: dev
  name: dev
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: LimitRange
metadata:
    name: my-limit-range
    namespace: dev
spec:
    limits:
    - type: Container
      default:   #default limit. Value set on pod. #constraint limits violated
        cpu: "2"
        memory: 3000Mi
      defaultRequest: #default request. Value set on pod
        cpu: "0.3"
        memory: 300Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: dev
spec:
  hard:
    cpu: "3"
    memory: 3Gi
    limits.cpu: "7"
    limits.memory: 7Gi
    pods: "10"
    configmaps: "1"