apiVersion: v1
kind: LimitRange
metadata:
    name: my-limit-range
    namespace: dev
spec:
    limits:
    - type: Container
      max:
        cpu: "2"
        memory: 2Gi
      min:
        cpu: "0.5"
        memory: 500Mi
      default:   #default limit. Value set on pod
        cpu: "0.5"
        memory: 500Mi
      defaultRequest: #default request. Value set on pod
        cpu: "0.5"
        memory: 500Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: dev
spec:
  hard:
    cpu: "3"
    memory: 3Gi
    limits.cpu: "7"
    limits.memory: 7Gi
    pods: "10"
    configmaps: "1"