apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-utils
  name: pod-utils
spec:
  containers:
  - image: nginx
    name: pod-utils
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
